CREATE TABLE [dbo].[Orders]
(
	[Id] INT NOT NULL PRIMARY KEY, 
    [Status] VARCHAR(50) NOT NULL, 
    [CustomerId] INT NOT NULL, 
    [InboundEDIId] INT NOT NULL, 
    [OrderDate] DATETIME NOT NULL DEFAULT GETDATE(), 
    [OrderNumber] VARCHAR(50) NULL, 
    [VendorNumber] VARCHAR(50) NULL, 
    [OrderType] VARCHAR(50) NULL, 
    [ReferenceNo] VARCHAR(50) NULL, 
    [CustomerOrderNo] VARCHAR(50) NULL, 
    [ExternalId] VARCHAR(50) NULL, 
    [ShippingMethod] NVARCHAR(250) NULL, 
    [ShipToId] NVARCHAR(250) NULL, 
    [ShipToName] NVARCHAR(250) NULL, 
    [ShipToAddress1] NVARCHAR(250) NULL, 
    [ShipToAddress2] NVARCHAR(250) NULL, 
    [ShipToCity] NVARCHAR(250) NULL, 
    [ShipToState] NVARCHAR(50) NULL, 
    [ShipToZip] NVARCHAR(50) NULL,
    [ShipToCountry] NVARCHAR(250) NULL, 
    [ShipToEmail] NVARCHAR(50) NULL, 
    [ShipToPhone] NVARCHAR(50) NULL,
    [BillToId] NVARCHAR(250) NULL, 
    [BillToName] NVARCHAR(250) NULL, 
    [BillToAddress1] NVARCHAR(250) NULL, 
    [BillToAddress2] NVARCHAR(250) NULL, 
    [BillToCity] NVARCHAR(250) NULL, 
    [BillToState] NVARCHAR(50) NULL, 
    [BillToZip] NVARCHAR(50) NULL,
    [BillToCountry] NVARCHAR(250) NULL, 
    [BillToEmail] NVARCHAR(50) NULL, 
    [BillToPhone] NVARCHAR(50) NULL,
    [BuyerId] NVARCHAR(250) NULL, 
    [BuyerName] NVARCHAR(250) NULL, 
    [BuyerAddress1] NVARCHAR(250) NULL, 
    [BuyerAddress2] NVARCHAR(250) NULL, 
    [BuyerCity] NVARCHAR(250) NULL, 
    [BuyerState] NVARCHAR(50) NULL, 
    [BuyerZip] NVARCHAR(50) NULL,
    [BuyerCountry] NVARCHAR(250) NULL, 
    [BuyerEmail] NVARCHAR(50) NULL, 
    [BuyerPhone] NVARCHAR(50) NULL, 
    [IsStoreOrder] bit NOT NULL,
    [CreatedDate] DATETIME NOT NULL DEFAULT GETDATE(), 
    [CreatedBy] INT NOT NULL  
)
